let games = [
    [
        "A Plague Tale Innocence",
        "APTI.jpg",
        "Asobo Studio",
        "Focus Home Interactive",
        "2019",
        "13 hours",
        "Middle Ages. 14th century France. The fearsome black plague is sweeping the continent of Europe, leaving nothing but rotting corpses and panic. Amicia, a French noblewoman finds out her brother, Hugo, is gravely ill. She sets out with him on a journey and tries to keep him safe from the swarms of disease-carrying rats and the fierce forces of the religious French inquisition dead set on capturing Hugo.",
        "stealth • action • horror",
        "APTI1.jpg",
        "APTI2.jpg",
        "APTI3.jpg",
        "GOG"
    ],
    [
        "Beholder 2",
        "Beholder2.jpg",
        "Alawar Stargaze",
        "Alawar",
        "2018",
        "15 hours",
        "Congratulations! You’ve been hired by the government! Sure, our glorious nation doesn’t really give its citizens the right to choose its representatives but they would’ve probably voted for us either way! Since you’re a part of the governing body, your life will become so easy. Just don’t mind the backstabbing, the mutual betrayal, the snitches and the eventual loss of your own morals.",
        "simulation • dystopia • strategy",
        "Beholder2-1.jpg",
        "Beholder2-2.jpg",
        "Beholder2-3.jpg",
        "GOG"
    ],
    [
        "Deus Ex Game of the Year Edition",
        "DEGOTY.jpg",
        "Ion Storm",
        "Eidos Interactive",
        "2000",
        "29 hours",
        "The year is 2052 and the world is a dangerous and chaotic place. Terrorists operate openly - killing thousands; drugs, disease and pollution kill even more. The world's economies are close to collapse and the gap between the insanely wealthy and the desperately poor grows ever wider.",
        "stealth • FPS • RPG",
        "DEGOTY1.jpg",
        "DEGOTY2.jpg",
        "DEGOTY3.jpg",
        "GOG"
    ],
    [
        "Dredge",
        "Dredge.jpg",
        "Black Salt Games",
        "Team17",
        "2023",
        "19 hours",
        "A fisherman arrives in a small town that is part of a larger, more peculiar archipelago. All of whom are harboring strange secrets and horrors that most cannot imagine.",
        "simulation • horror • management",
        "Dredge1.jpg",
        "Dredge2.jpg",
        "Dredge3.jpg",
        "GOG"
    ],
    [
        "Ghost Song",
        "GhostSong.jpg",
        "Old Moon",
        "Humble Games",
        "2022",
        "13 hours",
        "On the desolate moon of Lorian, a long-dormant Deadsuit awakens from slumber. Journey beneath the surface on an atmospheric 2D adventure of self-discovery, ancient mysteries, and cosmic terror. Explore winding caverns and acquire new abilities to unearth this alien world’s long-buried secrets.",
        "metroidvania • horror • science-fiction",
        "GhostSong1.jpg",
        "GhostSong2.jpg",
        "GhostSong3.jpg",
        "GOG"
    ],
    [
        "GreedFall",
        "GreedFall.jpg",
        "Spiders",
        "Focus Entertainment",
        "2019",
        "42 hours",
        "De Sardet, a noble of the Merchant Congregation, prepares to travel to the newly-settled island of Teer Fradee. De Sardet's cousin, Prince Constantin d'Orsay, has been named governor of New Serene, the Congregation's capital on the island, with De Sardet to act as his Legate. The Congregation hopes that the exotic environment of Teer Fradee will yield a cure for the malichor, a deadly plague spreading on the continent.",
        "action • RPG • fantasy",
        "GreedFall1.jpg",
        "GreedFall2.jpg",
        "GreedFall3.jpg",
        "GOG"
    ],
    [
        "Grim Fandango Remastered",
        "GrimFandangoR.jpg",
        "Double Fine Productions",
        "Double Fine Productions",
        "2015",
        "12 hours",
        "A travel agent in the Land of the Dead stumbles across crime and corruption within his business.",
        "point & click • adventure • fantasy",
        "GrimFandangoR1.jpg",
        "GrimFandangoR2.jpg",
        "GrimFandangoR3.jpg",
        "GOG"
    ],
    [
        "Intravenous",
        "Intravenous.jpg",
        "Explosive Squat Games",
        "HypeTrain Digital",
        "2021",
        "9 hours",
        "Teeth-clenching stealth, followed by tactical hardcore gunplay for those not looking for a quiet way in. Intravenous redefines challenging stealth-action and will keep you on the edge of your seat!",
        "stealth • shooter • tactical",
        "Intravenous1.jpg",
        "Intravenous2.jpg",
        "Intravenous3.jpg",
        "GOG"
    ],
    [
        "Kao the Kangaroo",
        "KtK1.jpg",
        "Tate Multimedia",
        "Tate Multimedia",
        "2000",
        "5 hours",
        "Kao the Kangaroo is a 3D adventure game, first released in 2000. More than 30 levels, numerous funny characters, adjustable difficulty, and demanding gameplay attracted not only young players, but also offered pleasant entertainment for more advanced players.",
        "adventure • platformer",
        "KtK1-1.jpg",
        "KtK1-2.jpg",
        "KtK1-3.jpg",
        "GOG"
    ],
    [
        "Kao the Kangaroo: Round 2",
        "KtK2.jpg",
        "Tate Multimedia",
        "Tate Multimedia",
        "2003",
        "6 hours",
        "Kao the Kangaroo returns to chase after his nemesis, Hunter, once more. The stakes are bigger, Kao's friends have been captured and their lives are in danger.",
        "adventure • platformer",
        "KtK2-1.jpg",
        "KtK2-2.jpg",
        "KtK2-3.jpg",
        "GOG"
    ],
    [
        "Kao the Kangaroo: Mystery of the Volcano",
        "KtKMotV.jpg",
        "Tate Multimedia",
        "Tate Multimedia",
        "2005",
        "4 hours",
        "Kao the Kangaroo: Mystery of the Volcano is a third installment of the epic Kao the Kangaroo 3D platformer series where the player takes control of a brave Kao, who embarks on a journey to save his homeland from an erupting volcano. Help him succeed!",
        "adventure • platformer",
        "KtKMotV1.jpg",
        "KtKMotV2.jpg",
        "KtKMotV3.jpg",
        "GOG"
    ],
    [
        "LIMBO",
        "LIMBO.jpg",
        "Playdead",
        "Playdead",
        "2011",
        "4 hours",
        "Uncertain of his sister's fate, a boy enters LIMBO.",
        "puzzle • platformer",
        "LIMBO1.jpg",
        "LIMBO2.jpg",
        "LIMBO3.jpg",
        "GOG"
    ],
    [
        "Metal Gear Solid",
        "MGS.jpg",
        "Konami Computer Entertainment Japan",
        "Konami",
        "1998",
        "13 hours",
        "A crack government anti-terrorist squad takes over an obscure Alaskan nuclear disposal facility. Solid Snake is up for the task to infiltrate the facility, rescue the two hostages and thwart the terrorists' plans.",
        "action • stealth • tactical",
        "MGS1.jpg",
        "MGS2.jpg",
        "MGS3.jpg",
        "GOG"
    ],
    [
        "Middle-Earth: Shadow of War",
        "MESoW.jpg",
        "Monolith Productions",
        "Warner Bros. Games",
        "2017",
        "36 hours",
        "The sequel to the critically acclaimed Middle-Earth: Shadow of Mordor (2014) features an original story with the return of Talion and Celebrimbor, who must go behind enemy lines to forge an army and turn all of Mordor against the Dark Lord Sauron.",
        "action • RPG • fantasy",
        "MESoW1.jpg",
        "MESoW2.jpg",
        "MESoW3.jpg",
        "GOG"
    ],
    [
        "Moonscars",
        "Moonscars.jpg",
        "Black Mermaid",
        "Humble Games",
        "2022",
        "12 hours",
        "Under grim moonlight, the fierce clayborne warrior Grey Irma battles, driven by a lonesome purpose: Find the Sculptor, and unravel the mystery of her existence.",
        "souls-like • metroidvania • action",
        "Moonscars1.jpg",
        "Moonscars2.jpg",
        "Moonscars3.jpg",
        "GOG"
    ],
    [
        "Scorn",
        "Scorn.jpg",
        "Ebb Software",
        "Kepler Interactive",
        "2022",
        "6 hours",
        "Scorn is an atmospheric first-person horror adventure game set in a nightmarish universe of odd forms and somber tapestry.",
        "horror • action • science-fiction",
        "Scorn1.jpg",
        "Scorn2.jpg",
        "Scorn3.jpg",
        "GOG"
    ],
    [
        "Shadow Warrior 2",
        "SW2.jpg",
        "Flying Wild Hog",
        "Devolver Digital",
        "2016",
        "16 hours",
        "Set five years after the events of the previous game. Lo Wang now lives in the wildlands as a hired sword. Demons, and humans under the command of nemesis Orochi Zilla now live side by side and both are out for his blood.",
        "action • FPS • looter shooter",
        "SW2-1.jpg",
        "SW2-2.jpg",
        "SW2-3.jpg",
        "GOG"
    ],
    [
        "Syberia: The World Before",
        "STWB.jpg",
        "Microids Studio Paris",
        "Microids",
        "2022",
        "14 hours",
        "Unravel the intertwined fates of Kate Walker, a New-York attorney whose life was turned around by the call to adventure, and Dana Roze, a young and promising pianist in Vaghen whose career is threatened by the shadow of the Second World War.",
        "adventure • point & click",
        "STWB1.jpg",
        "STWB2.jpg",
        "STWB3.jpg",
        "GOG"
    ],
    [
        "The Talos Principle",
        "TTalosP.jpg",
        "Croteam",
        "Devolver Digital",
        "2014",
        "21 hours",
        "As if awakening from a deep sleep, you find yourself in a strange, contradictory world of ancient ruins and advanced technology. Tasked by your creator with solving a series of increasingly complex puzzles, you must decide whether to have faith or to ask the difficult questions: Who are you? What is your purpose? And what are you going to do about it?",
        "puzzle • sci-fi • philosophical",
        "TTalosP1.jpg",
        "TTalosP2.jpg",
        "TTalosP3.jpg",
        "GOG"
    ],
    [
        "VirtuaVerse",
        "Virtuaverse.jpg",
        "Theta Division",
        "Blood Music",
        "2020",
        "12 hours",
        "VirtuaVerse is a challenging old school cyberpunk point & click adventure set in a future not so far away narrating tales of technomancers, AVR graffiti writers, hacker groups, tribes of cryptoshamans, digital archeology, epic cyberwars and virtual reality debauchery.",
        "point & click • cyberpunk • dystopia",
        "Virtuaverse1.jpg",
        "Virtuaverse2.jpg",
        "Virtuaverse3.jpg",
        "GOG"
    ],
    [
        "Yes, Your Grace",
        "YYG.jpg",
        "Brave at Night",
        "No More Robots",
        "2020",
        "9 hours",
        "These are troubling times, Your Grace. The petitioners’ petty matters exceed our limited resources, to say nothing of the war. A careful balance must be struck. Your throne awaits.",
        "medieval • indie",
        "YYG1.jpg",
        "YYG2.jpg",
        "YYG3.jpg",
        "GOG"
    ],
    [
        "Among the Sleep: Enhanced Edition",
        "AtS.jpg",
        "Krillbite Studio",
        "Krillbite Studio",
        "2017",
        "3 hours",
        "Among the Sleep is a first person horror adventure, in which you play a two year old child. After waking up in the middle of the night to mysterious sounds, you start exploring the dark looking for comfort.",
        "horror • adventure",
        "ATS1.jpg",
        "ATS2.jpg",
        "AtS3.jpg",
        "Epic"
    ],
    [
        "Axiom Verge",
        "AxiomVerge.jpg",
        "Thomas Happ Games LLC",
        "Thomas Happ Games LLC",
        "2015",
        "14 hours",
        "After a lab accident, a scientist awakens in a mysterious, alien world. Is this a distant planet? The far future? Or a complex virtual-reality computer simulation? Plumb the recesses of a large, labyrinthine world in order to learn its secrets and uncover your role within it. Discover tons of weapons, items, and abilities, each with their own unique behaviors and usage. You’ll need your wits to find them all.",
        "metroidvania • platformer • science-fiction",
        "AxiomVerge1.jpg",
        "AxiomVerge2.jpg",
        "AxiomVerge3.jpg",
        "Epic"
    ],
    [
        "Borderlands 3",
        "Borderlands3.jpg",
        "Gearbox Software",
        "2K",
        "2020",
        "46 hours",
        "In this FPS/RPG, Troy and Tyreen Calypso learn of other Vaults beyond the planet Pandora, and form a violent cult named the 'Children of the Vault' to gain possession of them, while Lilith recruits the 'Vault Hunter' to get to them first.",
        "looter shooter • RPG • FPS",
        "Borderlands3-1.jpg",
        "Borderlands3-2.jpg",
        "Borderlands3-3.jpg",
        "Epic"
    ],
    [
        "Castlevania Anniversary Collection",
        "CastlevaniaAC.jpg",
        "KONAMI",
        "KONAMI",
        "2019",
        "26 hours",
        "Released as part of the Konami 50th Anniversary celebration, relive these timeless classics that helped define the platformer genre. From the Belmont clan to their extended bloodlines and allies, the Castlevania Anniversary Collection is the best first step for anyone to take into the world of Castlevania and the fight against Dracula!",
        "action • platformer • metroidvania",
        "CastlevaniaAC1.jpg",
        "CastlevaniaAC2.jpg",
        "CastlevaniaAC3.jpg",
        "Epic"
    ],
    [
        "Celeste",
        "Celeste.jpg",
        "Maddy Makes Games Inc.",
        "Maddy Makes Games Inc.",
        "2018",
        "15 hours",
        "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the mystery of the mountain.",
        "precision platformer",
        "Celeste1.jpg",
        "Celeste2.jpg",
        "Celeste3.jpg",
        "Epic"
    ],
    [
        "Darksiders Warmastered Edition",
        "DarksidersWE.jpg",
        "KAIKO",
        "THQ Nordic",
        "2016",
        "21 hours",
        "Deceived by the forces of evil into prematurely bringing about the end of the world, War – the first Horseman of the Apocalypse – stands accused of breaking the sacred law by inciting a war between Heaven and Hell.",
        "action • adventure • hack & slash",
        "DarksidersWE1.jpg",
        "DarksidersWE2.jpg",
        "DarksidersWE3.jpg",
        "Epic"
    ],
    [
        "Darksiders II: Deathinitive Edition",
        "Darksiders2DE.jpg",
        "Gunfire Games",
        "THQ Nordic",
        "2015",
        "30 hours",
        "Become the terrifying force which everything fears but nothing can escape. Awakened by the End of Days, Death, the most feared of the legendary Four Horsemen embarks on a quest to redeem his brother's name. Along the way, the Horseman discovers that an ancient grudge may threaten all of Creation. Death lives!",
        "action • RPG • hack & slash",
        "Darksiders2DE1.jpg",
        "Darksiders2DE2.jpg",
        "DarksidersDE3.jpg",
        "Epic"
    ],
    [
        "Death's Door",
        "DeathsDoor.jpg",
        "Acid Nerve",
        "Devolver Digital",
        "2021",
        "12 hours",
        "Reaping souls of the dead and punching a clock might get monotonous but it's honest work for a Crow. The job gets lively when your assigned soul is stolen and you must track down a desperate thief to a realm untouched by death - where creatures grow far past their expiry.",
        "souls-like • RPG",
        "DeathsDoor1.jpg",
        "DeathsDoor2.jpg",
        "DeathsDoor3.jpg",
        "Epic"
    ],
    [
        "Death's Gambit: Afterlife",
        "DeathsGambitAfterlife.jpg",
        "White Rabbit",
        "Serenity Forge",
        "2018",
        "20 hours",
        "The promise of immortality lies at the heart of Siradon. As Death's right hand, challenge the undying guardians of the realm and endure the eternal struggle to purge their souls.",
        "souls-like • RPG • metroidvania",
        "DeathsGambitAfterlife1.jpg",
        "DeathsGambitAfterlife2.jpg",
        "DeathsGambitAfterlife3.jpg",
        "Epic"
    ],
    [
        "Dragon Age: Inquisition",
        "DragonAgeInquisition.jpg",
        "BioWare",
        "Electronic Arts",
        "2014",
        "93 hours",
        "A cataclysmic event plunges the land of Thedas into turmoil. Dragons darken the sky, casting a shadow of terror over a once-peaceful kingdom. Mages break into all-out war against the oppressive Templars. Nations rise against one another. It falls to you and your party of legendary heroes to restore order as you lead the Inquisition, hunting down the agents of chaos. Bonds will form - and some will break - as the campaign for truth takes its toll.",
        "action • RPG • fantasy",
        "DragonAgeInquisition1.jpg",
        "DragonAgeInquisition2.jpg",
        "DragonAgeInquisition3.jpg",
        "Epic"
    ],
    [
        "Dying Light: Enhanced Edition",
        "DyingLightDE.jpg",
        "Techland",
        "Techland",
        "2015",
        "47 hours",
        "Kyle Crane, a GRE agent, gets mixed out between the conflicts of the bandits and the runners in the city of Harran overrun by a vicious outbreak.",
        "action • zombies • horror",
        "DyingLightDE1.jpg",
        "DyingLightDE2.jpg",
        "DyingLightDE3.jpg",
        "Epic"
    ],
    [
        "Ghostwire Tokyo",
        "GhostwireTokyo.jpg",
        "Tango Gameworks",
        "Bethesda Softworks",
        "2022",
        "23 hours",
        "Tokyo's population has vanished, and deadly supernatural forces prowl the streets. Use an arsenal of elemental abilities to unravel the truth behind the disappearance and save Tokyo.",
        "horror • supernatural",
        "GhostwireTokyo1.jpg",
        "GhostwireTokyo2.jpg",
        "GhostwireTokyo3.jpg", 
        "Epic"
    ],
    [
        "Inside",
        "Inside.jpg",
        "Playdead",
        "Playdead",
        "2016",
        "4 hours",
        "Hunted and alone, a boy finds himself drawn into the center of a dark project.",
        "puzzle • platformer",
        "Inside1.jpg",
        "Inside2.jpg",
        "Inside3.jpg",
        "Epic"
    ],
    [
        "Just Cause 4",
        "JustCause4.jpg",
        "Avalanche Studios",
        "Square Enix",
        "2018",
        "28 hours",
        "Rogue agent Rico Rodriguez journeys to Solis, a huge South American world home of conflict, oppression and extreme weather conditions. Strap into your wingsuit, equip your fully customizable grappling hook, and get ready to bring the thunder!",
        "action • shooter",
        "JustCause4-1.jpg",
        "JustCause4-2.jpg",
        "JustCause4-3.jpg",
        "Epic"
    ],
    [
        "Kao the Kangaroo",
        "KtKN.jpg",
        "Tate Multimedia",
        "Tate Multimedia",
        "2022",
        "8 hours",
        "Inspired by the golden age of 3D Platformers, Kao The Kangaroo returns in a whole new adventure. Embark on an epic journey, master magical gloves, explore lush environments and take Kao through his most grand tale yet.",
        "3D platformer • action • adventure",
        "KtKN1.jpg",
        "KtKN2.jpg",
        "KtKN3.jpg",
        "Epic"
    ],
    [
        "Marvel's Midnight Suns",
        "MMidnightSuns.jpg",
        "Firaxis Games",
        "2K",
        "2022",
        "64 hours",
        "Set in the darker side of the Marvel Universe, putting you face-to-face against demonic forces of the underworld as you team up with and live among the Midnight Suns, Earth's last line of defense.",
        "deckbuilding • turn-based combat • superhero",
        "MMidnightSuns1.jpg",
        "MMidnightSuns2.jpg",
        "MMidnightSuns3.jpg",
        "Epic"
    ],
    [
        "Metro 2033 Redux",
        "M2033Redux.jpg",
        "4A Games",
        "Deep Silver",
        "2014",
        "12 hours",
        "In 2013 the world was devastated by an apocalyptic event, annihilating almost all mankind and turning the Earth's surface into a poisonous wasteland. A handful of survivors took refuge in the depths of the Moscow underground, and human civilization entered a new Dark Age. The year is 2033.",
        "post-apocalypse • FPS • horror",
        "M2033Redux1.jpg",
        "M2033Redux2.jpg",
        "M2033Redux3.jpg",
        "Steam"
    ],
    [
        "NioH Complete Edition",
        "NioHCE.jpg",
        "Koei Tecmo",
        "Koei Tecmo",
        "2017",
        "75 hours",
        "Ready to die? Experience the newest brutal action game from Team NINJA and Koei Tecmo Games. In the age of samurai, a lone traveler lands on the shores of Japan. He must fight his way through the vicious warriors and supernatural Yokai that infest the land in order to find that which he seeks.",
        "souls-like • RPG • fantasy",
        "NioHCE1.jpg",
        "NioHCE2.jpg",
        "NioHCE3.jpg",
        "Epic"
    ],
    [
        "Sable",
        "Sable.jpg",
        "Shedworks",
        "Raw Fury",
        "2021",
        "14 hours",
        "Embark on an unique and unforgettable journey and guide Sable through her Gliding; a rite of passage that will take her across vast deserts and mesmerizing landscapes, capped by the remains of spaceships and ancient wonders.",
        "sci-fi • exploration • adventure",
        "Sable1.jpg",
        "Sable2.jpg",
        "Sable3.jpg",
        "Epic"
    ],
    [
        "Saints Row IV: Re-Elected",
        "SRIVR.jpg",
        "Deep Silver Volition",
        "Deep Silver",
        "2013",
        "26 hours",
        "The Boss of the Saints has been elected to the Presidency of the United States but the Saints are just getting started. After a catastrophic alien invasion of Earth, the Saints have been transported to a bizarro-Steelport simulation. With homies new and old, and an arsenal of superpowers and strange weapons, they must fight to free humanity from alien overlord Zinyak and his alien empire, saving the world in the wildest open world game ever.",
        "sci-fi • action",
        "SRIVR1.jpg",
        "SRIVR2.jpg",
        "SRIVR3.jpg",
        "Epic"
    ],
    [
        "Sniper Ghost Warrior Contracts",
        "SniperGWC.jpg",
        "Underdog Studio",
        "CI Games",
        "2019",
        "15 hours",
        "Become the ultimate assassin in the most realistic modern warfare sniping game available. Engage in an immersive single-player campaign across large, open-ended maps. Tactical thinking, stealth approach and precision in execution of long shots required.",
        "action • sniper • stealth",
        "SniperGWC1.jpg",
        "SniperGWC2.jpg",
        "SniperGWC3.jpg",
        "Epic"
    ],
    [
        "Sonic Mania",
        "SonicMania.jpg",
        "Christian Whitehead",
        "SEGA",
        "2017",
        "9 hours",
        "Following the events of Sonic & Knuckles (1994), Sonic and Tails receive a energy reading from Angel Island and board their biplane to investigate. However, Doctor Eggman sends an elite group of EggRobos to reach the signal before Sonic and Tails.",
        "platformer • action",
        "SonicMania1.jpg",
        "SonicMania2.jpg",
        "SonicMania3.jpg",
        "Epic"
    ],
    [
        "Subnautica",
        "Subnautica.jpg",
        "Unknown Worlds Entertainment",
        "Unknown Worlds Entertainment",
        "2018",
        "43 hours",
        "Descend into the depths of an alien underwater world filled with wonder and peril. Craft equipment, pilot submarines and out-smart wildlife to explore lush coral reefs, volcanoes, cave systems, and more - all while trying to survive.",
        "survival • horror • science-fiction",
        "Subnautica1.jpg",
        "Subnautica2.jpg",
        "Subnautica3.jpg",
        "Epic"
    ],
    [
        "SUPERHOT",
        "SUPERHOT.jpg",
        "SUPERHOT Team",
        "SUPERHOT Team",
        "2016",
        "5 hours",
        "SUPERHOT is the smash-hit FPS where time moves only when you move. No regenerating health bars. No conveniently placed ammo drops. It's you, alone, outnumbered and outgunned. Snatch weapons from fallen enemies to shoot, slice and dodge through a truly cinematic hurricane of slow-motion bullets.",
        "action • FPS",
        "SUPERHOT1.jpg",
        "SUPERHOT2.jpg",
        "SUPERHOT3.jpg",
        "Epic"
    ],
    [
        "The Callisto Protocol",
        "TheCallistoProtocol.jpg",
        "Striking Distance Studios",
        "KRAFTON, Inc.",
        "2022",
        "12 hours",
        "A crashed cargo pilot struggles to survive against horrific mutating prisoners on Jupiters moon.",
        "science fiction • horror • action",
        "TheCallistoProtocol1.jpg",
        "TheCallistoProtocol2.jpg",
        "TheCallistoProtocol3.jpg",
        "Epic"
    ],
    [
        "The Evil Wthin 2",
        "TEW2.jpg",
        "Tango Gameworks",
        "Bethesda Softworks",
        "2017",
        "19 hours",
        "Detective Sebastian Castellanos has lost everything, including his daughter, Lily. To save her, he must descend into the nightmarish world of STEM. Horrifying threats emerge from every corner, and he must rely on his wits to survive. For his one chance at redemption, the only way out is in.",
        "horror • action",
        "TEW2-1.jpg",
        "TEW2-2.jpg",
        "TEW2-3.jpg",
        "Epic"
    ],
    [
        "The Outer Worlds: Spacer's Choice Edition",
        "TOWSCE.jpg",
        "Obsidian Entertainment",
        "Private Division",
        "2023",
        "37 hours",
        "Lost in transit while on a colonist ship bound for the furthest edge of the galaxy, you awake decades later only to find yourself in the midst of a deep conspiracy threatening to destroy the Halcyon colony. As you explore the furthest reaches of space and encounter various factions, all vying for power, the character you decide to become will determine how this player-driven story unfolds. In the corporate equation for the colony, you are the unplanned variable.",
        "action • RPG • science-fiction",
        "TOWSCE1.jpg",
        "TOWSCE2.jpg",
        "TOWSCE3.jpg",
        "Epic"
    ],
    [
        "Thief",
        "Thief.jpg",
        "Eidos-Montréal",
        "Eidos Interactive Corp.",
        "2014",
        "23 hours",
        "Garrett, the Master Thief, steps out of the shadows into the City. In this treacherous place, where the Baron’s Watch spreads a rising tide of fear and oppression, his skills are the only things he can trust. Even the most cautious citizens and their best-guarded possessions are not safe from his reach.",
        "stealth • action • adventure",
        "Thief1.jpg",
        "Thief2.jpg",
        "Thief3.jpg",
        "Epic"
    ],
    [
        "Trek to Yomi",
        "TrekToYomi.jpg",
        "Leonard Menchiari",
        "Devolver Digital",
        "2022",
        "6 hours",
        "As a vow to his dying Master, the young swordsman Hiroki is sworn to protect his town and the people he loves against all threats. Faced with tragedy and bound to duty, the lone samurai must voyage beyond life and death to confront himself and decide his path forward.",
        "action • hack & slash • adventure",
        "TrekToYomi1.jpg",
        "TrekToYomi2.jpg",
        "TrekToYomi3.jpg",
        "Epic"
    ],
    [
        "Wolfenstein: The New Order",
        "WolfensteinTNO.jpg",
        "MachineGames",
        "Bethesda Softworks",
        "2014",
        "16 hours",
        "After regaining consciousness following an injury sustained in World War II, legendary American commando, B.J. Blazkowicz, awakens from a coma in a dystopian Nazi dominated world of 1960s. He tries to locate the remnants of the resistance.",
        "action • FPS",
        "WolfensteinTNO1.jpg",
        "WolfensteinTNO2.jpg",
        "WolfensteinTNO3.jpg",
        "Epic"
    ],
    [
        "LEGO Star Wars: The Skywalker Saga",
        "LSWSS.jpg",
        "TT Games",
        "Warner Bros. Games",
        "2022",
        "35 hours",
        "Play through all nine Skywalker saga films in a game unlike any other. With over 300 playable characters, over 100 vehicles, and 23 planets to explore, a galaxy far, far away has never been more fun!",
        "adventure • science-fiction",
        "LSWSS1.jpg",
        "LSWSS2.jpg",
        "LSWSS3.jpg",
        "Epic"
    ],
    [
        "Batman: The Enemy Within – The TellTale Series",
        "TBTEW.jpg",
        "Telltale",
        "Telltale",
        "2017",
        "11 hours",
        "In this latest chapter from the award-winning studio behind Batman - The Telltale Series, both Bruce Wayne and Batman will be forced into precarious new roles. The Riddler has returned to terrorize Gotham City, but his gruesome puzzles merely foreshadow an even greater crisis.",
        "adventure • superhero",
        "TBTEW1.jpg",
        "TBTEW2.jpg",
        "TBTEW3.jpg",
        "Steam"
    ],
    [
        "Blasphemous",
        "Blasphemous.jpg",
        "The Game Kitchen",
        "Team17",
        "2019",
        "20 hours",
        "Play as The Penitent One - a sole survivor of the massacre of the ‘Silent Sorrow’. Trapped in an endless cycle of death and rebirth, it’s down to you to free the world from this terrible fate and reach the origin of your anguish.",
        "metroidvania • souls-like",
        "Blasphemous1.jpg",
        "Blasphemous2.jpg",
        "Blasphemous3.jpg",
        "Steam"
    ],
    [
        "Borderlands: The Pre-Sequel",
        "BorderlandsTPS.jpg",
        "Gearbox Software",
        "2K",
        "2014",
        "30 hours",
        "Discover the story behind Borderlands 2 villain, Handsome Jack, and his rise to power. Taking place between the original Borderlands and Borderlands 2, the Pre-Sequel gives you a whole lotta new gameplay featuring the genre blending fusion of shooter and RPG mechanics that players have come to love.",
        "looter shooter • FPS • action",
        "BorderlandsTPS1.jpg",
        "BorderlandsTPS2.jpg",
        "BorderlandsTPS3.jpg",
        "Steam"
    ],
    [
        "Catherine Classic",
        "Catherine.jpg",
        "ATLUS",
        "SEGA",
        "2019",
        "17 hours",
        "Explore the pleasures and horrors of love as Vincent, a man with a hard choice to make: marry his long-time girlfriend Katherine or move on to the incredible blonde he just woke up next to — named Catherine!",
        "anime • puzzle",
        "Catherine1.jpg",
        "Catherine2.jpg",
        "Catherine3.jpg",
        "Steam"
    ],
    [
        "Control Ultimate Edition",
        "ControlUE.jpg",
        "Remedy Entertainment",
        "505 Games",
        "2020",
        "26 hours",
        "A corruptive presence has invaded the Federal Bureau of Control…Only you have the power to stop it. The world is now your weapon in an epic fight to annihilate an ominous enemy through deep and unpredictable environments. Containment has failed, humanity is at stake. Will you regain control?",
        "action • science-fiction • supernatural",
        "ControlUE1.jpg",
        "ControlUE2.jpg",
        "ControlUE3.jpg",
        "Steam"
    ],
    [
        "Cuphead",
        "Cuphead.jpg",
        "Studio MDHR Entertainment Inc.",
        "Studio MDHR Entertainment Inc.",
        "2017",
        "16 hours",
        "Play as Cuphead or Mugman (in single player or local co-op) as you traverse strange worlds, acquire new weapons, learn powerful super moves, and discover hidden secrets while you try to pay your debt back to the devil!",
        "platformer • shoot & run",
        "Cuphead1.jpg",
        "Cuphead2.jpg",
        "Cuphead3.jpg",
        "Steam"
    ],
    [
        "Devil May Cry 4 Special Edition",
        "DMC4.jpg",
        "CAPCOM",
        "CAPCOM",
        "2015",
        "17 hours",
        "A young knight named Nero comes to grips with his newly found power as his beliefs and allegiance are tested when he witnesses Sparda's legendary son Dante slaughter his fellow warriors.",
        "action • hack and slash",
        "DMC4-1.jpg",
        "DMC4-2.jpg",
        "DMC4-3.jpg",
        "Steam"
    ],
    [
        "DOOM",
        "DooM.jpg",
        "id Software",
        "Bethesda Softworks",
        "2016",
        "17 hours",
        "You’ve come here for a reason. The Union Aerospace Corporation’s massive research facility on Mars is overwhelmed by fierce and powerful demons, and only one person stands between their world and ours. As the lone DOOM Marine, you’ve been activated to do one thing – kill them all.",
        "action • FPS • science-fiction",
        "DooM1.jpg",
        "DooM2.jpg",
        "DooM3.jpg",
        "Steam"
    ],
    [
        "Enemy Front",
        "EnemyFront.jpg",
        "CI Games",
        "CI Games",
        "2014",
        "8 hours",
        "Enemy Front is the game which is a story of resistance in Occupied Europe against Nazi Germany, from the French resistance fighters to Warsaw Uprising.",
        "action • FPS • history",
        "EnemyFront1.jpg",
        "EnemyFront2.jpg",
        "EnemyFront3.jpg",
        "Steam"
    ],
    [
        "Far Cry 3",
        "FarCry3.jpg",
        "Ubisoft Montreal",
        "Ubisoft",
        "2012",
        "26 hours",
        "While skydiving, Jason Brody and his friends land on an island overrun by pirates, where Jason is torn between fighting for the Rakyat resistance and rescuing his friends.",
        "action • FPS",
        "FarCry3-1.jpg",
        "FarCry3-2.jpg",
        "FarCry3-3.jpg",
        "Steam"
    ],
    [
        "Assassin's Creed: Syndicate",
        "ACSyndicate.jpg",
        "Ubisoft Quebec",
        "Ubisoft",
        "2015",
        "34 hours",
        "London, 1868. In the heart of the Industrial Revolution, lead your underworld organization and grow your influence to fight those who exploit the less privileged in the name of progress.",
        "action • history",
        "ACSyndicate1.jpg",
        "ACSyndicate2.jpg",
        "ACSyndicate3.jpg",
        "PS"
    ],
    [
        "Alan Wake 2",
        "AlanWake2.jpg",
        "Remedy Entertainment",
        "Epic Games",
        "2023",
        "26 hours",
        "13 years after bestselling writer Alan Wake went missing, a string of ritualistic murders occur in the town of Bright Falls, Washington. Saga Anderson, an FBI agent, is sent to Bright Falls to investigate the murders.",
        "horror • psychological",
        "AlanWake2-1.jpg",
        "AlanWake2-2.jpg",
        "AlanWake2-3.jpg",
        "PS"
    ],
    [
        "Aliens vs. Predators",
        "AvP2010.jpg",
        "Rebellion",
        "SEGA",
        "2010",
        "12 hours",
        "Weyland-Yutani research team discovers an ancient Predator Pyramid and hopes to unlock the advanced technology while studying the resident Aliens. However, when the Aliens escape, a unit of United States Colonial Marine Corps responds to neutralize the threat while the Predator Race also send three of their members to investigate.",
        "action • sci-fi • horror",
        "AvP2010-1.jpg",
        "AvP2010-2.jpg",
        "AvP2010-3.jpg",
        "Steam"
    ],
    [
        "Devil May Cry V",
        "DMCV.jpg",
        "Capcom",
        "Capcom",
        "2019",
        "17 hours",
        "Years have passed since the legions of hell have set foot in this world, but now a new demonic invasion has begun, and humanity's last hope will rest in the hands of three lone demon hunters, each offering a radically different play style.",
        "action • fantasy • hack and slash",
        "DMCV1.jpg",
        "DMCV2.jpg",
        "DMCV3.jpg",
        "Steam"
    ],
    [
        "Dark Souls II: Scholar of the First Sin",
        "DS2SotFS.jpg",
        "FromSoftware",
        "Bandai Namco",
        "2015",
        "62 hours",
        "A cursed warrior travels to Drangleic, the forgotten land of a once-great king, hoping to find a cure before going insane.",
        "action • fantasy • RPG",
        "DS2SotFS1.jpg",
        "DS2SotFS2.jpg",
        "DS2SotFS3.jpg",
        "PS"
    ],
    [
        "Dark Souls III",
        "DS3.jpg",
        "FromSoftware",
        "Bandai Namco",
        "2016",
        "53 hours",
        "The fire is fading. Darkness creeps across the land. The Lords of Cinder charged with watching over the First Flame have abandoned their thrones. The Champion of Ash, an undead is chosen to return them to their thrones.",
        "action • fantasy • RPG",
        "DS3-1.jpg",
        "DS3-2.jpg",
        "DS3-3.jpg",
        "PS"
    ],
    [
        "Dark Souls Remastered",
        "DSRemastered.jpg",
        "FromSoftware",
        "Bandai Namco",
        "2018",
        "44 hours",
        "After narrowly escaping a doomed fate in an asylum, an undead warrior fights his way through the desolate remains of Lordran, once a sprawling utopia lead by the gods, to seek his purpose and fulfill a centuries old prophecy.",
        "action • fantasy • RPG",
        "DSRemastered1.jpg",
        "DSRemastered2.jpg",
        "DSRemastered3.jpg",
        "PS"
    ],
    [
        "Ender Lilies",
        "EnderLilies.jpg",
        "Live Wire, Adglobe",
        "Binary Haze Interactive",
        "2021",
        "19 hours",
        "Once upon a time, in the Kingdom of End, the Deathly Rain suddenly started to fall, transforming all living things it touched into bloodthirsty corpses. In an instant, the realm fell into chaos. The cursed rain never stopped pouring on the remaining ruins - In the depth of an old forgotten church, Lily opens her eyes.",
        "metroidvania • action • fantasy",
        "EnderLilies1.jpg",
        "EnderLilies2.jpg",
        "EnderLilies3.jpg",
        "Epic"
    ],
    [
        "Final Fantasy VII",
        "FFVII.jpg",
        "Square Enix",
        "Square Enix",
        "1997",
        "50 hours",
        "A former soldier from an evil company joins a mercenary clan to fight the company he once served.",
        "sci-fi • action • RPG",
        "FFVII1.jpg",
        "FFVII2.jpg",
        "FFVII3.jpg",
        "Steam"
    ],
    [
        "Garden Story",
        "GardenStory.jpg",
        "Picogram",
        "Rose City Games",
        "2021",
        "11 hours",
        "Embark on a wholesome adventure to save The Grove! Forage resources, combat the invasive Rot, and restore the community. Relax and enjoy the fruits of your labor in this charming action-RPG starring a grape.",
        "fantasy • adventure",
        "GardenStory1.jpg",
        "GardenStory2.jpg",
        "GardenStory3.jpg",
        "Epic"
    ],
    [
        "Gothic",
        "Gothic1.jpg",
        "Piranha Bytes",
        "THQ Nordic",
        "2001",
        "31 hours",
        "War has been waged across the kingdom of Myrtana. Orcish hordes invaded human territory and the king of the land needed a lot of ore to forge enough weapons, should his army stand against this threat. Whoever breaks the law in these darkest of times is sentenced to serve in the giant penal colony of Khorinis, mining the so much needed...",
        "fantasy • RPG • action",
        "Gothic1-1.jpg",
        "Gothic1-2.jpg",
        "Gothic1-3.jpg",
        "Steam"
    ],
    [
        "Gothic 2",
        "Gothic2.jpg",
        "Piranha Bytes",
        "THQ Nordic",
        "2005",
        "58 hours",
        "Rescued from the ruins of the temple of the sleeper, the nameless hero faces another great challenge when Beliar, one of the three gods, summons a tremendous army in the mine valley.",
        "fantasy • RPG • action",
        "Gothic2-1.jpg",
        "Gothic2-2.jpg",
        "Gothic2-3.jpg",
        "Steam"
    ],
    [
        "Gothic 3",
        "Gothic3.jpg",
        "Piranha Bytes",
        "THQ Nordic",
        "2006",
        "68 hours",
        "Orcs won the war and enslaved the humans that wouldn't acknowledge their rule. There are now three main factions on Myrtana: the rebels, the orcs, and the mysterious assassin guild.",
        "fantasy • RPG • action",
        "Gothic3-1.jpg",
        "Gothic3-2.jpg",
        "Gothic3-3.jpg",
        "Steam"
    ],
    [
        "Halo: The Master Chief Collection",
        "Halo.jpg",
        "Bungie, 343 Industries",
        "Xbox Game Studios",
        "2019",
        "43 hours",
        "The Master Chief’s iconic journey includes six games, built for PC and collected in a single integrated experience. Whether you’re a long-time fan or meeting Spartan 117 for the first time, The Master Chief Collection is the definitive Halo gaming experience.",
        "action • FPS • sci-fi",
        "Halo1.jpg",
        "Halo2.jpg",
        "Halo3.jpg",
        "Steam"
    ],
    [
        "Hitman",
        "Hitman.jpg",
        "IO Interactive",
        "Square Enix",
        "2016",
        "24 hours",
        "When Agent 47 joins the ICA to hunt down threats to mankind, he is also pulled into a game of Cat and Mouse against a mysterious organization that is determined to stop him. All the while he is being stalked by someone from his past.",
        "stealth • action",
        "Hitman1.jpg",
        "Hitman2.jpg",
        "Hitman3.jpg",
        "PS"
    ],
    [
        "Horizon: Zero Dawn - Complete Edition",
        "HZDCE.jpg",
        "Guerrilla Games",
        "Sony Computer Entertainment",
        "2020",
        "53 hours",
        "In a primitive tribal world where strange, monstrous, animalistic machines roam the wilderness, a brave young female warrior goes on a quest to learn the truth about her mysterious origin and the state the world is in.",
        "RPG • sci-fi • post-apocalypse",
        "HZDCE1.jpg",
        "HZDCE2.jpg",
        "HZDCE3.jpg",
        "PS"
    ],
    [
        "inFamous Second Son",
        "IFSS.jpg",
        "Sucker Punch Studios",
        "Sony Computer Entertainment",
        "2014",
        "15 hours",
        "Delsin Rowe, a rebellious youngster in Seattle becomes aware of his incredible powers after a confrontation with an escaped inmate. But when his abilities come under the attention of the D.U.P., he is faced to battle them.",
        "action • sci-fi • superpowers",
        "IFSS1.jpg",
        "IFSS2.jpg",
        "IFSS3.jpg",
        "PS"
    ],
    [
        "It Takes Two",
        "ItTakesTwo.jpg",
        "Hazelight Studios",
        "Electronic Arts",
        "2021",
        "14 hours",
        "The clashing couple Cody and May are turned into dolls by a magic book. Together, trapped in a fantastical world where the unpredictable hides around every corner, they are reluctantly challenged with saving their fractured relationship.",
        "platformer • adventure • co-op",
        "ItTakesTwo1.jpg",
        "ItTakesTwo2.jpg",
        "ItTakesTwo3.jpg",
        "Steam"
    ],
    [
        "Judgment",
        "Judgment.jpg",
        "Ryu Ga Gotoku Studio",
        "SEGA",
        "2018",
        "46 hours",
        "Fight for the truth and uncover the twisted crime running deep beneath the surface of Tokyo. In this legal thriller , the balance between justice and mercy teeters on the edge.",
        "action • brawler • RPG",
        "Judgment1.jpg",
        "Judgment2.jpg",
        "Judgment3.jpg",
        "Steam"
    ],
    [
        "KINGDOM HEARTS -HD 1.5+2.5 ReMIX-",
        "KH1525.jpg",
        "Square Enix",
        "Square Enix",
        "2017",
        "155 hours",
        "KINGDOM HEARTS -HD 1.5+2.5 ReMIX- is an HD remastered collection of 6 unforgettable KINGDOM HEARTS experiences. Take up your Keyblade to save the Disney worlds from darkness.",
        "action • RPG • adventure",
        "KH1525-1.jpg",
        "KH1525-2.jpg",
        "KH1525-3.jpg",
        "PS"
    ],
    [
        "Max Payne 2: The Fall of Max Payne",
        "MaxPayne2.jpg",
        "Remedy Entertainment",
        "Rockstar Games",
        "2003",
        "8 hours",
        "The brooding cop has left the DEA and returned to the NYPD. When his latest case ends up involving the thought-dead femme fatale Mona Sax, he finds that his journey through the night is far from over.",
        "action • FPS • noir",
        "MaxPayne2-1.jpg",
        "MaxPayne2-2.jpg",
        "MaxPayne2-3.jpg",
        "Steam"
    ],
    [
        "Metaphor ReFantazio",
        "MReFantazio.jpg",
        "Atlus",
        "SEGA",
        "2024",
        "87 hours",
        "The throne sits empty after the king’s assassination. With no heirs, the will of the late king decrees that the next monarch will be elected by the people, & thus begins your fight for the throne…",
        "fantasy • RPG • turn-based",
        "MReFantazio1.jpg",
        "MReFantazio2.jpg",
        "MReFantazio3.jpg",
        "Steam"
    ],
    [
        "Pathologic Classic HD",
        "PathologicCHD.jpg",
        "Ice Pick Lodge, General Arcade",
        "Good Shepherd Entertainment",
        "2015",
        "43 hours",
        "Three people try to uncover the source of a lethal virus in a mystical eerie Eastern European village at the turn of the 20th century.",
        "survival • psychological • horror",
        "PathologicCHD1.jpg",
        "PathologicCHD2.jpg",
        "PathologicCHD3.jpg",
        "Steam"
    ],
    [
        "Planescape: Torment - Enhanced Edition",
        "PlanescapeTEE.jpg",
        "Beamdog",
        "Beamdog",
        "2017",
        "42 hours",
        "In the city of Sigil, the only place from which all realities of the Planescape universe can be reached, an immortal amnesiac, the Nameless One, must uncover his past, the mystery of his immortality as well as who's trying to kill him.",
        "fantasy • cRPG • psychological",
        "PlanescapeTEE1.jpg",
        "PlanescapeTEE2.jpg",
        "PlanescapeTEE3.jpg",
        "Steam"
    ],
    [
        "Risen 2: Dark Waters",
        "Risen2DW.jpg",
        "Piranha Bytes",
        "THQ Nordic",
        "2012",
        "34 hours",
        "Set several years after the end of Risen, raging titans have devastated the world and pushed humanity to the brink of existence. Subsequently, monstrous creatures have risen from the watery depths of the sea and their attacks have brought all seafaring to a grinding halt.",
        "pirates • RPG • fantasy",
        "Risen2DW1.jpg",
        "Risen2DW2.jpg",
        "Risen2DW3.jpg",
        "Steam"
    ],
    [
        "Stories: The Path of Destinies",
        "StoriesTPoD.jpg",
        "Spearhead Games",
        "Spearhead Games",
        "2016",
        "8 hours",
        "Reynardo the Fox is a clever rogue, but he's not as clever as he thinks. He's got himself sucked into a Rebellion against the mad Emperor, and now he's got fateful choices to make. Should he rescue his oldest friend, the shiftless Lapino; wield a gem cursed by a dead god; or resurrect a weapon lost at the beginning of time? Worse, he's still in love with the Emperor's adopted daughter, who he met in sword fu school. He's got dozens of ways to screw this up; but can he find a way to win his war?",
        "adventure • action • fantasy",
        "StoriesTPoD1.jpg",
        "StoriesTPoD2.jpg",
        "StoriesTPoD3.jpg",
        "Steam"
    ],
    [
        "The Elder Scrolls V: Skyrim - Special Edition",
        "TESVSkyrim.jpg",
        "Bethesda Game Studios",
        "Bethesda Softworks",
        "2016",
        "113 hours",
        "After escaping execution, the last living Dragonborn must grow in strength and power to defeat the dragons that have once again begun to plague the land of Skyrim.",
        "fantasy • RPG • action",
        "TESVSkyrim1.jpg",
        "TESVSkyrim2.jpg",
        "TESVSkyrim3.jpg",
        "Steam"
    ],
    [
        "This Is The Police 2",
        "TITP2.jpg",
        "Weappy Studio",
        "THQ Nordic",
        "2018",
        "26 hours",
        "Grim adventure/strategy game about Jack Boyd, a disgraced ex police chief who teams up with the new idealistic female sheriff of a small snowy town where he's hiding to fix everything - only to end up on an even darker path than before.",
        "strategy • turn-based • action",
        "TITP2-1.jpg",
        "TITP2-2.jpg",
        "TITP2-3.jpg",
        "Steam"
    ],
    [
        "The Order: 1886",
        "TO1866.jpg",
        "Ready At Dawn",
        "Sony Computer Entertainment",
        "2015",
        "9 hours",
        "The Order: 1886 is set in an alternate history of London, where an old order of knights keep all of the world safe from half breed monsters, who are a combination of animal and man.",
        "action • shooter • fantasy",
        "TO1866-1.jpg",
        "TO1866-2.jpg",
        "TO1866-3.jpg",
        "PS"
    ],
    [
        "The Vanishing of Ethan Carter",
        "TVoEC.jpg",
        "The Astronauts",
        "The Astronauts",
        "2014",
        "4 hours",
        "Paul Prospero, a detective who receives a disturbing letter from Ethan Carter who has vanished in the wake of a brutal murder which Paul quickly figures out might not be the only local murder worth looking into.",
        "mystery • adventure • detective",
        "TVoEC1.jpg",
        "TVoEC2.jpg",
        "TVoEC3.jpg",
        "Steam"
    ],
    [
        "Assassin's Creed Chronicles: India",
        "ACCIndia.jpg",
        "Climax Studios",
        "Ubisoft Entertainment",
        "2016",
        "8 hours",
        "Embody Arbaaz in his quest for retribution through a colorful depiction of Colonial India in 2.5D stealth gameplay.",
        "adventure • 2.5D platformer • stealth",
        "ACCIndia1.jpg",
        "ACCIndia2.jpg",
        "ACCIndia3.jpg",
        "Ubisoft"
    ],
    [
        "Assassin's Creed Chronicles: Russia",
        "ACCRussia.jpg",
        "Climax Studios",
        "Ubisoft Entertainment",
        "2016",
        "8 hours",
        "Join Nikolaï Orelov in his search for redemption as you journey through an iconic, propaganda art style Russia in 2.5D gameplay.",
        "adventure • 2.5D platformer • stealth",
        "ACCRussia1.jpg",
        "ACCRussia2.jpg",
        "ACCRussia3.jpg",
        "Ubisoft"
    ],
    [
        "Child of Light",
        "ChildOL.jpg",
        "Ubisoft Montreal",
        "Ubisoft", 
        "2014",
        "14 hours",
        "Aurora, a young girl from 1895 Austria, awakens on the lost fairytale continent of Lemuria. To return home she must fight against the dark creatures of the Queen of the Night, who have stolen the sun, the moon and the stars. At stake is not only Lemuria, but Aurora’s true destiny.",
        "turn-based • RPG • fantasy",
        "ChildOL1.jpg",
        "ChildOL2.jpg",
        "ChildOL3.jpg",
        "Ubisoft"
    ],
    [
        "Prince of Persia: The Forgotten Sands",
        "POPTFS.jpg",
        "Ubisoft Montreal",
        "Ubisoft",
        "2010",
        "9 hours",
        "Prince of Persia The Forgotten Sands is the next chapter in the fan-favorite Sands of Time universe. Visiting his brother's kingdom following his adventure in Azad, the Prince finds the royal palace under siege from a mighty army bent on its destruction.",
        "action • fantasy • puzzle-platformer",
        "POPTFS1.jpg",
        "POPTFS2.jpg",
        "POPTFS3.jpg",
        "Ubisoft"
    ],
    [
        "Prince of Persia: The Sands of Time",
        "POPTSOT.jpg",
        "Ubisoft Montreal",
        "Ubisoft",
        "2003",
        "10 hours",
        "Amidst the scorched sands of ancient Persia, there is a legend spun in an ancient tongue. It speaks of a time borne by blood and ruled by deceit. Drawn to the dark powers of a magic dagger, a young Prince is led to unleash a deadly evil upon a beautiful kingdom.",
        "action • fantasy • puzzle-platformer",
        "POPTSOT1.jpg",
        "POPTSOT2.jpg",
        "POPTSOT3.jpg",
        "Ubisoft"
    ],
    [
        "Prince of Persia: The Two Thrones",
        "POPTTT.jpg",
        "Ubisoft Montreal",
        "Ubisoft",
        "2005",
        "11 hours",
        "The Prince of Persia, a seasoned warrior, returns from the Island of Time to Babylon with his love, Kaileena. Instead of the peace that he longs for, he finds his homeland ravaged by war and the kingdom turned against him.",
        "action • fantasy • puzzle-platformer",
        "POPTTT1.jpg",
        "POPTTT2.jpg",
        "POPTTT3.jpg",
        "Ubisoft"
    ],
    [
        "Prince of Persia: Warrior Within",
        "POPWW.jpg",
        "Ubisoft Montreal",
        "Ubisoft",
        "2004",
        "15 hours",
        "Enter the dark underworld of Prince of Persia Warrior Within, the sword-slashing sequel to the critically acclaimed Prince of Persia: The Sands of Time™. Hunted by Dahaka, an immortal incarnation of Fate seeking divine retribution, the Prince embarks upon a path of both carnage and mystery to defy his…",
        "action • fantasy • puzzle-platformer",
        "POPWW1.jpg",
        "POPWW2.jpg",
        "POPWW3.jpg",
        "Ubisoft"
    ],
    [
        "Doom Eternal",
        "DEternal.jpg",
        "id Software",
        "Bethesda Softworks",
        "2020",
        "21 hours",
        "Hell’s armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.",
        "action • sci-fi • FPS",
        "DEternal1.jpg",
        "DEternal2.jpg",
        "DEternal3.jpg",
        "Xbox"
    ],
    [
        "Legacy of Kain: Defiance",
        "LoKD.jpg",
        "Crystal Dynamics",
        "Crystal Dynamics",
        "2003",
        "15 hours",
        "Take control of two powerful and highly evolved vampires: Kain, an all-powerful demigod, and Raziel, a demonic angel of death. Each equipped with a legendary sword, Kain & Raziel must battle through a world loaded with conflict and intrigue as they attempt to unravel their destinies.",
        "action • adventure • fantasy",
        "LoKD1.jpg",
        "LoKD2.jpg",
        "LoKD3.jpg",
        "GOG"
    ],
    [
        "Mafia III: Definitive Edition",
        "Mafia3DE.jpg",
        "Hangar 13",
        "2K",
        "2020",
        "41 hours",
        "After Lincoln Clay's surrogate family, the black mob, is betrayed and killed by the Italian Mafia, Lincoln builds a new family and blazes a path of revenge through the Mafioso responsible.",
        "mafia • crime • action",
        "Mafia3DE1.jpg",
        "Mafia3DE2.jpg",
        "Mafia3DE3.jpg",
        "GOG"
    ],
    [
        "Wolfenstein: The Old Blood",
        "WolfensteinTOB.jpg",
        "Machine Games",
        "Bethesda Softworks",
        "2015",
        "9 hours",
        "Set in 1946, follows a man as he tries to discover the locations of a Nazi compound and sabotage Helga Von Schabbs's plans.",
        "world war 2 • FPS • zombies",
        "WolfensteinTOB1.jpg",
        "WolfensteinTOB2.jpg",
        "WolfensteinTOB3.jpg",
        "Xbox"
    ],
    [
        "1000xRESIST", 
        "1000xRESIST.jpg",
        "sunset visitor 斜陽過客",
        "Fellow Traveller",
        "2024",
        "13 hours",
        "1000xRESIST is a thrilling sci-fi adventure. The year is unknown, and a disease spread by an alien invasion keeps you underground. You are Watcher. You dutifully fulfil your purpose in serving the ALLMOTHER, until the day you discover a shocking secret that changes everything.",
        "sci-fi • thriller",
        "1000xRESIST1.jpg",
        "1000xRESIST2.jpg",
        "1000xRESIST3.jpg",
        "Steam"
    ],
    [
        "Star Wars: The Knights of the Old Republic",
        "SWKOTOR.jpg",
        "BioWare",
        "LucasArts",
        "2003",
        "37 hours",
        "It is four thousand years before the Galactic Empire and hundreds of Jedi Knights have fallen in battle against the ruthless Sith. You are the last hope of the Jedi Order. Can you master the awesome power of the Force on your quest to save the Republic? Or will you fall to the lure of the dark side?",
        "sci-fi • RPG",
        "SWKOTOR1.jpg",
        "SWKOTOR-2.jpg",
        "SWKOTOR3.jpg",
        "Steam"
    ],
    [
        "Star Wars: The Knights of the Old Republic II – The Sith Lords",
        "SWKOTOR2.jpg",
        "Obsidian Entertainment",
        "LucasArts",
        "2005",
        "41 hours",
        "5 years after the events of the award winning original, the Sith are on the verge of crushing the Old Republic. As a lone Jedi, will you follow the light side or succumb to the dark?",
        "sci-fi • RPG",
        "SWKOTOR2-1.jpg",
        "SWKOTOR2-2.jpg",
        "SWKOTOR2-3.jpg",
        "Steam"
    ],
    [
        "Castlevania: Lords of Shadow – Ultimate Edition",
        "CLoSUE.jpg",
        "MercurySteam",
        "KONAMI",
        "2013",
        "26 hours",
        "Castlevania: Lords of Shadow – Ultimate Edition is the complete edition of Castlevania: Lords of Shadow, a dark and vivid new re-imagining of the Castlevania mythology. It is the end of days and ungodly powers isolate the Earth.",
        "fantasy • action • adventure",
        "CLoSUE1.jpg",
        "CLoSUE2.jpg",
        "CLoSUE3.jpg",
        "Steam"
    ]
]

let number, length;
length = games.length;

function choose(){
    number = Math.floor(Math.random()*length);
    document.getElementById("cover").src = 'img/covers/' + games[number][1];
    document.getElementById("gameTitle").innerHTML = games[number][0] + ' ' + '<img id="platform" src="" alt="" />';
    document.getElementById("gameDetails").innerHTML = '<i class="fa-solid fa-code"></i> ' + games[number][2] + "   " + '<i class="fa-solid fa-paper-plane"></i> ' + games[number][3] + "   " + '<i class="fa-solid fa-calendar"></i> ' + games[number][4] + "   " + '<i class="fa-solid fa-clock"></i> ' + games[number][5];
    document.getElementById("gameDesc").innerHTML = games[number][6];
    document.getElementById("gameTags").innerHTML = games[number][7];
    document.getElementById("screen1").src = 'img/screen/' + games[number][8];
    document.getElementById("screen2").src = 'img/screen/' + games[number][9];
    document.getElementById("screen3").src = 'img/screen/' + games[number][10];
    if (games[number][11] == "Steam") {
        document.getElementById("platform").src = "img/logos/Steam.png";
        document.getElementById("platform").title = "Steam";
    }
    else if (games[number][11] == "Epic") {
        document.getElementById("platform").src = "img/logos/EGS.png";
        document.getElementById("platform").title = "Epic Games";
    }
    else if (games[number][11] == "Ubisoft") {
        document.getElementById("platform").src = "img/logos/Ubisoft.png";
        document.getElementById("platform").title = "Ubisoft Connect";
    }
    else if (games[number][11] == "GOG") {
        document.getElementById("platform").src = "img/logos/GOG.png";
        document.getElementById("platform").title = "GOG Galaxy";
    }
    else if (games[number][11] == "PS") {
        document.getElementById("platform").src = "img/logos/PS.png";
        document.getElementById("platform").title = "PlayStation";
    }
    else if (games[number][11] == "Switch") {
        document.getElementById("platform").src = "img/logos/NSwitch.png";
        document.getElementById("platform").title = "Nintendo Switch";
    }
    else if (games[number][11] == "Xbox") {
        document.getElementById("platform").src = "img/logos/Xbox.png";
        document.getElementById("platform").title = "Xbox App";
    }
    else if (games[number][11] == "DRMFree" {
        document.getElementById("platform").src = "img/logos/drmfree.png";
        document.getElementById("platform").title = "DRM-free";
    }
}
